"""Render docs/reference/cli.md from the argparse definitions (tests/test_cli.py checks it is current).

    python scripts/gen_cli_reference.py            # rewrite the page
    python scripts/gen_cli_reference.py --check    # exit 1 if the page is stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from linchpin.cli import build_parser

ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "docs" / "reference" / "cli.md"

HEADER = """# CLI reference

<!-- generated by scripts/gen_cli_reference.py from src/linchpin/cli.py; do not edit by hand -->

`linchpin <global options> <command> ...` (or `python -m linchpin`). Every command prints JSON on stdout;
warnings and errors go to stderr. LINCHPIN only reads files: it sends no packets.

State: `ingest` and `scenario` write the findings to the state file (default `.linchpin/findings.json`, env
`LINCHPIN_STATE`); `scenario`, and `ingest` with a topology YAML that sets config keys, also store a
`config.json` next to it, which then overrides `--config`. Every analysis command rebuilds the attack graph
from the state deterministically.

"""

FOOTER = """
## Configuration file

```yaml
weights: {w1: 0.5, w2: 0.3, w3: 0.2}
skill_penalty: {network_exploit: 0.1, cred_reuse: 0.2, client_side: 0.4, privesc: 0.3, acl_abuse: 0.25}
entrypoints: ["auto:internet_facing"]          # or host ids
crown_jewels: ["auto:sensitivity=high"]        # or node / host ids
k_shortest: 10
exploitability_source: intel                   # or: learned (M11 model score where present)
fix_cost: {Vuln: 1, Credential: 1, Ace: 1, Host: 3}   # effort weights for `cuts --weighted`
neo4j: {uri: "bolt://localhost:7687", user: neo4j}  # password only via NEO4J_PASSWORD
```

## Environment

| variable | used by | meaning |
| --- | --- | --- |
| `LINCHPIN_STATE` | all | default for `--state` |
| `LINCHPIN_CONFIG` | all | default for `--config` |
| `NEO4J_PASSWORD` | `neo4j-push` | Neo4j password (never read from the config file) |
| `LINCHPIN_SCENARIO`, `LINCHPIN_DATA_DIR`, ... | `serve` | see [HTTP API](api.md#limits-and-environment) |
"""


def _arg_rows(p: argparse.ArgumentParser) -> list[str]:
    rows = []
    for a in p._actions:  # argparse has no public API for this
        if isinstance(a, (argparse._HelpAction, argparse._SubParsersAction)):
            continue
        name = ", ".join(f"`{s}`" for s in a.option_strings) or f"`{a.dest}`"
        if a.option_strings and a.nargs != 0:
            name += f" `{a.metavar or a.dest.upper()}`"
        text = (a.help or "").replace("%(default)s", str(a.default)).replace("|", "\\|")
        if a.choices and "choices" not in text:
            text += f" (choices: {', '.join(map(str, a.choices))})"
        rows.append(f"| {name} | {text} |")
    return rows


def render() -> str:
    """The page text; usage lines are wrapped at a fixed width and never colourised (deterministic)."""
    import os
    os.environ["COLUMNS"] = "100"
    os.environ["NO_COLOR"] = "1"
    os.environ["PYTHON_COLORS"] = "0"
    ap = build_parser()
    out = [HEADER, "## Global options", "", "| option | meaning |", "| --- | --- |", *_arg_rows(ap), ""]
    sub = next(a for a in ap._actions if isinstance(a, argparse._SubParsersAction))
    helps = {c.dest: c.help for c in sub._choices_actions}
    out += ["## Commands", "", "| command | purpose |", "| --- | --- |"]
    out += [f"| [`{name}`](#{name}) | {helps.get(name, '')} |" for name in sub.choices]
    for name, p in sub.choices.items():
        out += ["", f"### {name}", "", helps.get(name, "") + ".", "", "```text", p.format_usage().strip(), "```"]
        rows = _arg_rows(p)
        if rows:
            out += ["", "| argument | meaning |", "| --- | --- |", *rows]
    return "\n".join(out) + "\n" + FOOTER


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if the committed page differs")
    a = ap.parse_args(argv)
    text = render()
    if a.check:
        current = PAGE.read_text(encoding="utf-8") if PAGE.exists() else ""
        if current != text:
            print(f"{PAGE} is stale: run python scripts/gen_cli_reference.py", file=sys.stderr)
            return 1
        return 0
    PAGE.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {PAGE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
